version: '3.8'

services:
  frontend:
    build:
      context: frontend  # Путь к директории с Dockerfile фронтенда
    ports:
      - "3000:80"  # Порт хоста:порт контейнера
    depends_on:
      - web
    networks:
      - frontend
      - backend

  web:
    build:
      context: .  # Путь к директории с Dockerfile бэкенда
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:15
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["celery", "-A", "src.app.tasks.send_email.celery", "worker", "--loglevel=info"]
    env_file:
      - backend/.env
    depends_on:
      - redis
      - web
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend:
