version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "src.app.tasks.send_email.celery", "worker", "--loglevel=info"]
    env_file:
      - .env
    depends_on:
      - redis
      - web
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
